# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ecd956c30a6f5bc5b1f79b996c69a9b9b3517a62a51287d0caa3ace4d7d89fb8c349840fedb28595c1b9cfbdff3b2d5dbde9500881a3929289cea9fe71eddd

test:
  secret_key_base: 8a92b0e2ae9df6a69449fe9048703b99ec5bb86d343600afb43fb10bc93dca65bbd1ca07729397502e43867a68f5c8b618a37e36de9dc0c091a8d63ce93e8d12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
